theme: jekyll-theme-cayman
title: Stream Deck icon pack "System UIcons"
description: A free icon pack for the Elgato Stream Deck, based on the clear, concise and free System UIcons.
github:
  is_project_page: false
